### ISSUE TITLE
Add translatable "include" urls in README 

### ISSUE THREAD

**Issue by beaufortfrancois** [trapeze/transurlvania#4]
I think README should be more explicit about the fact that "include" urls have to be declared also as translatable. Here's what I would update in the README:

_To make an URL pattern localizable, first ensure that it is in the
`url(...)` form, then wrap the URL pattern itself in a gettext function
call:_

```
url(_(r'^$'), include('landing.urls')),
url(_(r'^about-us/$'), 'about_us', name='about_us'),
```

**Comment by greatestape** [comment]
I've tagged a new release that allows you to declare URL patterns without explicitly calling the url function.
